### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by nwolverson**

### CODE REVIEW

**Comment by paf31** [comment]
👍 yes please, this is required by `react-dom`

**Comment by hdgarrood** [comment]
Might be nice to also add a dev dependency on psci-support?

**Comment by hdgarrood** [comment]
Opps

**Comment by hdgarrood** [comment]
I'll merge this now, but since I'm away from my PC I can't tag or upload docs. I've added both of you as contributors, please feel free to make any other changes we might want and release them.

**Comment by nwolverson** [comment]
Tagged & published, thanks.

**Pull request merged**
